spring:
    mvc:
        hiddenmethod:
            filter: 
                enabled: true
    datasource:
        jndi-name: jdbc/UniversityDatabase
springdoc: 
    swagger-ui: 
        version: '@springdoc.version@'
    
        